name: Automatic Release

on:
  push:
    branches:
      - master

jobs:
  build-test-prep:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/andrewtriestocode/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: build and test
        run: dotnet test -c Release
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: setup semantic-release
        run: |
          npm install -D semantic-release
          npm install -D @semantic-release/git
          npm install -D @semantic-release/changelog
          npm install -D @semantic-release/exec
      - name: run semantic-release
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
      - uses: actions/checkout@v2
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/andrewtriestocode/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create the package
        run: dotnet pack --no-build --include-symbols --output nupkgs
      - name: Publish the package to GPR
        run: dotnet nuget push nupkgs/*.nupkg
