name: .NET

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Detect latest version
      run: |
        versionRegex='^v([0-9]+)\.([0-9]+)\.([0-9]+)'
        if [[ $(git describe --tags --abbrev=0) =~ $versionRegex ]]
        then
            echo "major=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "minor=${BASH_REMATCH[2]}" >> $GITHUB_ENV
            echo "patch=${BASH_REMATCH[3]}" >> $GITHUB_ENV
        else
            echo "No existing version tag found"
        fi
    - name: Determine change
      run: |
        commit="${{ github.event.head_commit.message }}"
        majorChangeRegex='^[^:]+\!:|BREAKING\ CHANGE:'
        minorChangeRegex='^feat:'
        patchChangeRegex='^fix:'
        bump=
        branch=
        if [[ $comment =~ $majorChangeRegex ]]
        then
            echo "Major change detected"
            major=$(($major + 1))
            echo "bump=1" >> $GITHUB_ENV
            echo "branch=1 >> $GITHUB_ENV
        elif [[ $comment =~ $minorChangeRegex ]]
        then
            echo "Minor change detected"
            minor=$(($minor + 1))
            echo "bump=1" >> $GITHUB_ENV
        elif [[ $comment =~ $patchChangeRegex ]]
        then
            echo "Patch change detected"
            patch=$(($patch + 1))
            echo "bump=1" >> $GITHUB_ENV
        else
            echo "No change detected"
        fi
        echo "newVersion=${major}.${minor}.${patch}" >> $GITHUB_ENV
    - name: Tag release
      if: env.bump == 1
      run: git tag v${newVersion}
    - name: Create release branch
      if: env.branch == 1
      run: git branch release/v${newVersion}
    - name: Build
      if: env.bump == 1
      run: dotnet build -c Release
    - name: Test
      if: env.bump == 1
      run: dotnet test --no-build
    - name: Pack
      if: env.bump == 1
      run: dotnet pack --no-build -c Release -o  packages
    - name: Deploy
      if: env.bump == 1
      run: dotnet nuget push
