name: Automatic Release

on:
  pullrequest:
    types: [opened, reopened, synchronize, 

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup .net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: build and test
        run: |
          dotnet restore
          dotnet build -c Release --no-restore
          dotnet test --no-build -c Release
